services:
  selenium-hub: # this the name of lable we can add any name but keep the name relatable
    image: 'selenium/hub:4.33.0' #this is the actual image
    container_name: selenium-hub
    ports:
      - '5552:4442'
      - '5553:4443'
      - '5555:4444'
    networks:
      - selenium-grid
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  chrome:
    image: 'selenium/node-chrome:4.33.0'
    shm_size: 8gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - TZ=America/Chicago
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - selenium-grid
    ports:
      - '5900:5900'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  edge:
    image: 'selenium/node-edge:4.33.0'
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - TZ=America/Chicago
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - selenium-grid
    ports:
      - '5901:5900'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
#
#  firefox:
#    image: 'selenium/node-firefox:4.33.0'
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SCREEN_WIDTH=1920
#      - SCREEN_HEIGHT=1080
#      - TZ=America/Chicago
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#    networks:
#      - selenium-grid
#    ports:
#      - '5902:5900'
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"

networks:
  selenium-grid:
    driver: bridge
